[2024-07-29T04:57:07.245+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-29T04:57:07.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.print_random_quote manual__2024-07-29T04:56:53.245444+00:00 [queued]>
[2024-07-29T04:57:07.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.print_random_quote manual__2024-07-29T04:56:53.245444+00:00 [queued]>
[2024-07-29T04:57:07.278+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-29T04:57:07.423+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): print_random_quote> on 2024-07-29 04:56:53.245444+00:00
[2024-07-29T04:57:07.427+0000] {standard_task_runner.py:64} INFO - Started process 226 to run task
[2024-07-29T04:57:07.429+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'print_random_quote', 'manual__2024-07-29T04:56:53.245444+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmph4u4mx64']
[2024-07-29T04:57:07.430+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask print_random_quote
[2024-07-29T04:57:07.602+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_dag.print_random_quote manual__2024-07-29T04:56:53.245444+00:00 [running]> on host e58db608bc3e
[2024-07-29T04:57:07.864+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='print_random_quote' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T04:56:53.245444+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-29T04:56:53.245444+00:00'
[2024-07-29T04:57:07.864+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-29T04:57:08.789+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-29T04:57:08.789+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/welcome_dag.py", line 15, in print_random_quote
    quote = response.json()['content']
            ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'content'
[2024-07-29T04:57:08.801+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=welcome_dag, task_id=print_random_quote, run_id=manual__2024-07-29T04:56:53.245444+00:00, execution_date=20240729T045653, start_date=20240729T045707, end_date=20240729T045708
[2024-07-29T04:57:08.954+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task print_random_quote ('content'; 226)
[2024-07-29T04:57:08.966+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-29T04:57:08.980+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-29T04:57:08.981+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
